name: fooddash
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  animated_shimmer: ^1.0.0
  dio: ^5.4.3+1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^7.0.1
  flutter_native_splash: ^2.3.10
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  geolocator: ^13.0.1
  go_router: ^14.4.1
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  mask_input_formatter: ^0.0.3
  shared_preferences: ^2.2.3
  socket_io_client: ^3.0.1

dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/icons/tabs/
    - assets/images/

  fonts:
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/sofia-pro/SofiaPro-Black.otf
          weight: 800
        - asset: assets/fonts/sofia-pro/SofiaPro-Bold.otf
          weight: 700
        - asset: assets/fonts/sofia-pro/SofiaPro-SemiBold.otf
          weight: 600
        - asset: assets/fonts/sofia-pro/SofiaPro-Medium.otf
          weight: 500
        - asset: assets/fonts/sofia-pro/SofiaPro-Regular.otf
          weight: 400
        - asset: assets/fonts/sofia-pro/SofiaPro-Light.otf
          weight: 300
        - asset: assets/fonts/sofia-pro/SofiaPro-ExtraLight.otf
          weight: 200

flutter_native_splash:
  color: "#FE724C"
  image: assets/app/splash.png

  android_12:
    image: assets/app/android12splash.png
    color: "#FE724C"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/icon.png"
  min_sdk_android: 21
